### ISSUE TITLE
Mer.Lie. - 1

### ISSUE THREAD

**Issue by 00mcf00** [NataliaArdilez/MLiebre#1]
Home:
Las imágenes en el home tienen diferentes tamaños y están amontonadas, sería bueno que estén separadas y tengan el mismo tamaño
El camión no está centrado con el círculo
No tiene ninguna animación, ni el sombreado, ni el movimiento del camión ni el cambio de color de los iconos del footer
El "Basado en tu última visita" y "Ofertas" en vez de estar a la izquierda deberían estar arriba de las imágenes
No se puede escribir en la barra del buscador

En register:
Habría que reacomodar los tamaños de los renglones, quedaron muy exagerados
Más armonía en los tamaños de letra (capaz se compensa al arreglar los renglones)

**Comment by NataliaArdilez** [comment]
¡Listo! Cambios realizados.

**Comment by NataliaArdilez** [comment]
¡Listo! Cambios realizados.
